// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_lugotech.Data;

namespace backend_lugotech.Migrations
{
    [DbContext(typeof(EmpleadoContext))]
    partial class EmpleadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend_lugotech.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APELLIDO")
                        .IsRequired()
                        .HasColumnName("APELLIDO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CARGO")
                        .IsRequired()
                        .HasColumnName("CARGO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DEPARTAMENTO")
                        .IsRequired()
                        .HasColumnName("DEPARTAMENTO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DIRECCION")
                        .IsRequired()
                        .HasColumnName("DIRECCION")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FECHA_NACIMIENTO")
                        .HasColumnName("FECHA_NACIMIENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PERSONAS_CONTACTOS")
                        .HasColumnName("PERSONAS_CONTACTOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SALARIO")
                        .HasColumnName("SALARIO")
                        .HasColumnType("float");

                    b.Property<string>("TELEFONO")
                        .IsRequired()
                        .HasColumnName("TELEFONO")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("ID");

                    b.ToTable("EMPLEADO");
                });
#pragma warning restore 612, 618
        }
    }
}
